config/routes.rb
Rails.application.routes.draw do

  resources :homepage, controller: 'homepage', only: [:index]

  get 'homepage/resume', to: 'homepage#download'

  post 'homepage/contact', to: 'homepage#send_contact'

  get '*path' => redirect('/')

  root 'homepage#index'
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :phone
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  # Nickname must be a blank field, indicated by captcha, used to prevent spam
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Portfolio - #{name} is contacting me",
      :to => "djgerhab@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    # Setting up model for the Contact Form
    @contact = Contact.new
  end

  def download
    send_file 'downloads/Daniel_Gerhab_Resume.pdf', type: 'application/pdf', disposition: 'attachment'
  end

  def send_contact
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver # delivers if is not a spam and is valid
      flash.now[:notice] = 'Thank you for your message. I will read it!'
    else
      flash.now[:alert] = 'Cannot send message.'
    end
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/_about.html.erb
<section class="section about waypoint" data-slide="1">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <header class="title">
          <h2 class="title-section wow fadeInDown">ABOUT ME</h2>
          <div class="separator-wrapper wow fadeIn">
            <div class="separator-first-circle">
              <div class="separator-second-circle"></div>
            </div>
          </div>
          <p class="subtitle wow fadeInDown">I am regarded as a technological professional. Skilled in numerous programming languages and applications to make technology better.</p>
        </header>
      </div>
      <div class="clearfix"></div>
      <div class="col-xs-12 col-sm-6 col-md-5 col-lg-5 wow fadeInDown" data-wow-delay="500ms">
        <div class="box-resume">
          <div class="center-top">
            <%= image_tag 'about-img.jpg', class: 'img-responsive' %>
          </div>
          <ul>
            <li><span>Name</span> Daniel Gerhab</li>
            <li><span>Email</span> <a href="mailto:djgerhab@gmail.com" title="" class="email">djgerhab@gmail.com</a></li>
            <li><span>Phone</span> <a href="tel:+16107625375" class="phone">(610)-762-5375</a></li>
          </ul>
          <div class="center-bottom">
            <a href="<%= homepage_resume_path %>" title="Download Resume" class="download-resume btn btn-default btn-primary" data-turbolinks="false">Download Resume</a>
          </div>
        </div>
      </div>
      <%= render partial: 'homepage/skills' %>
      <div class="clearfix"></div>
      <%= render partial: 'homepage/experience' %>
      <%= render partial: 'homepage/education' %>
    </div>
  </div>
</section>

app/views/homepage/_banner.html.erb
<section class="section banner waypoint" data-slide="0">
  <div class="wrap-overlay"></div>
</section>

app/views/homepage/_connect.html.erb
<section class="section connect waypoint" data-slide="3">
  <div class="container">
    <div class="row">
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <header class="title">
          <h2 class="title-section wow fadeInDown">CONNECT</h2>
          <div class="separator-wrapper wow fadeIn">
            <div class="separator-first-circle">
              <div class="separator-second-circle"></div>
            </div>
          </div>
          <p class="subtitle wow fadeInDown">If you want to know more about me, feel free to connect with other sites</p>
        </header>
      </article>
      <div class="clearfix"></div>
      <%= render partial: 'shared/map' %>
      <div class="clearfix"></div>
    </div>
  </div>
</section>
<section class="section social-group">
  <div class="container">
    <div class="row">
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 wow fadeInDown">
        <a href="https://www.facebook.com/djgerhab" title="Facebook Page">
          <div class="item">
            <i class="fab fa-facebook"></i>
          </div>
        </a>
        <a href="https://gitlab.com/djgerhab/portfolio" title="GitLab Project Page">
          <div class="item">
            <i class="fab fa-git"></i>
          </div>
        </a>
        <a href="https://www.linkedin.com/in/danielgerhab" title="LinkedIn Page">
          <div class="item">
            <i class="fab fa-linkedin"></i>
          </div>
        </a>
      </article>
    </div>
  </div>
</section>

app/views/homepage/_contact.html.erb
<section class="section contact waypoint" data-slide="2">
  <div class="container">
    <div class="row">
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <header class="title">
          <h2 class="title-section wow fadeInDown">CONTACT</h2>
          <div class="separator-wrapper wow fadeIn">
            <div class="separator-first-circle">
              <div class="separator-second-circle"></div>
            </div>
          </div>
          <p class="subtitle wow fadeInDown">If you are interested in my profile and have questions and/or business opportunities, please feel free to reach out to me.</p>
        </header>
      </article>
      <div class="clearfix"></div>
      <%= render partial: 'shared/contact_form' %>
    </div>
  </div>
</section>

app/views/homepage/_education.html.erb
<section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="years">
    <div class="subsection-title wow fadeInDown">
    <div class="separator-first-circle">
      <div class="separator-second-circle"></div>
    </div>
    EDUCATION
    </div>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="year">
          2006 <hr />2004
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Bloomsburg University</h4>
          <p class="subtitle">Bloomsburg, PA</p>
          <p>Graduated in 2006 with a Bachelors degree in Computer Information Systems</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="year">
          2004 <hr />2002
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Northampton Community College</h4>
          <p class="subtitle">Bethlehem, PA</p>
          <p>Started my undergraduate studies in CIS before transferring to Bloomsburg</p>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/homepage/_experience.html.erb
<section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="years">
    <div class="subsection-title wow fadeInDown">
    <div class="separator-first-circle">
      <div class="separator-second-circle"></div>
    </div>
    EMPLOYMENT
    </div>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="year">
          Present <hr />2021
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Carmax</h4>
          <p class="subtitle">Senior Software Engineer</p>
          <p>Part of a large team creating a wholesale online auction experience.</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="year">
          2021 <hr />2016
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Kroll Bond Rating Agency</h4>
          <p class="subtitle">Senior Software Engineer</p>
          <p>Building financial web applications for large investment companies.</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="year">
          2016 <hr />2015
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>eBay Enterprise</h4>
          <p class="subtitle">Senior Mid-Tier Software Engineer</p>
          <p>Worked on an Order Management Enterprise application that is client facing and integrates the companies numerous backend APIs through one central interface.</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="year">
          2015 <hr />2011
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>eBay Enterprise</h4>
          <p class="subtitle">UI Lead Developer</p>
          <p>Lead a team of UI engineers to build and maintain major retailers E-Commerce webstores such as Sony, Petsmart, Steinmart</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="year">
          2011 <hr />2007
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Deluxe Digital Studios</h4>
          <p class="subtitle">Java Developer</p>
          <p>Programmed the functionality and interactivity (Menus, Animations, Games) of Blu-ray discs for major clients such as Universal Studios, Fox MGM, Paramount and Disney.</p>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/homepage/_skills.html.erb
<section class="col-xs-12 col-sm-6 col-md-7 col-lg-7 wow fadeInDown">
  <p class="leads">My Career Goals</p>
  <p>To use my education and 15+ years of experience as a Software Engineer to obtain a related position that will fulfill my career goals of finding a secure, well paid employment that offers everyday challenges to keep my problem solving ambitions alive!</p>
  <div class="skills">
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="icon">
          <i class="fas fa-language"></i>
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Languages</h4>
          <p>Javascript, Ruby, PHP, Typescript, Python, C#, Java, CSS, JSP, C++, HTML5</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="icon">
          <i class="fas fa-university"></i>
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Frameworks</h4>
          <p>React, Node.js, Next.js, Rails, .NET, Angular, RxJs, Redux, Apollo GraphQL, Auth0, Jest, Cypress, Sass, jQuery, Bootstrap, D3</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="icon">
          <i class="fas fa-rocket"></i>
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Applications</h4>
          <p>Postman, Docker Desktop, Vagrant, Virtual Box, Figma, Photoshop, VSCode, Webstorm, Vim, Mobster</p>
        </div>
      </div>
    </article>
    <article class="row item wow fadeInDown">
      <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
        <div class="icon">
          <i class="fas fa-wrench"></i>
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
        <div class="desc">
          <h4>Other Tech / Tools</h4>
          <p>Azure Services, GraphQL, REST, Storybook, Webpack, AWS, CosmosDB, MySQL, MsSQL, Postgres, ElasticSearch (ELK Stack), Terraform, Docker Swarm, Portainer, Puppet, Datadog, Sonarqube, Trivy, Opsgenie, Swagger, Artifactory, Maven, Azure DevOps, Gitlab CI, Jenkins, Heroku, GoCD, Slack, Atlassian Products</p>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/homepage/index.html.erb
<div class="site-content">
  <%= render partial: 'homepage/banner' %>
  <%= render partial: 'shared/navbar' %>
  <%= render partial: 'shared/errors' %>
  <%= render partial: 'homepage/about' %>
  <%= render partial: 'homepage/contact' %>
  <%= render partial: 'homepage/connect' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: 'shared/head' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= yield %>
    <%= render partial: 'shared/footer' %>

    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBfb7oDYZrJHHQmJ6xdjLC7ydIKzmZne7A&callback=initMap&libraries=&v=weekly' %>
  </body>
</html>

app/views/shared/_contact_form.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="subsection-title wow fadeInDown">
    <div class="separator-first-circle">
      <div class="separator-second-circle"></div>
    </div>
    CONTACT FORM
  </div>
</div>
<%= form_for(@contact, url: homepage_contact_path, html: { class: 'contact-form wow fadeInDown', 'data-wow-delay' => '500ms'}) do |f| %>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <p><%= f.text_field(:name, class: 'form-control', placeholder: 'Name...') %></p>
    <p><%= f.telephone_field(:phone, class: 'form-control', placeholder: 'Phone...') %></p>
    <p><%= f.email_field(:email, class: 'form-control', placeholder: 'Email...') %></p>
    <p class="hidden"><%= f.text_field :nickname %></p>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <p><%= f.text_area(:message, rows: 6, class: 'form-control', placeholder: 'Message...') %></textarea></p>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="send">
      <%= f.submit( 'Send a Message', class: 'btn btn-default btn-primary') %>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<div class="flash-message-container">
  <% if notice.present? %>
    <p class="flash-message alert alert-success"><%= notice %></p>
  <% end %>
  <% if flash[:warning].present? %>
    <p class="flash-message alert alert-warning"><%= flash[:warning] %></p>
  <% end %>
  <% if alert.present? %>
    <p class="flash-message alert alert-danger"><%= alert %></p>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <p class="footer-text">Made by me, Daniel Gerhab</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Daniel Gerhab - Resume, Portfolio</title>

<%= favicon_link_tag 'favicon.png' %>
<%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

<!--[if lte IE 9]>
  <%# html5shiv allows html5 markup to work in ie %>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <%# respond.js provides responsive support to ie %>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <%= stylesheet_link_tag 'ie-9', media: 'all' %>
<![endif]-->

<%= csrf_meta_tags %>

app/views/shared/_map.html.erb
<section class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="maps-wraper wow fadeInDown">
    <div id="map">
      <!-- map -->
    </div>
  </div>
  <div class="maps-address wow fadeInDown">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <span class="fas fa-phone"></span><a href="tel:+16107625375" class="phone">(610)-762-5375</a>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <span class="fas fa-map-marker"></span> Pennsylvania
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <span class="fas fa-envelope"></span> <a href="mailto:djgerhab@gmail.com" title="" class="email">djgerhab@gmail.com</a>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default main-menu">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="index.html" rel="About Me" data-slide="0">
        <header class="logo">
          <h2>Daniel <span>Gerhab</span></h2>
          <div class="roles">
            <div>Passionate Coder</div>
            <div>Enthusiastic Learner</div>
            <div>Self-Driven Adventurer</div>
          </div>
        </header>
      </a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li data-slide="1"><a href="#" rel="About Me">About Me</a></li>
        <li data-slide="2"><a href="#" rel="Contact">Contact</a></li>
        <li data-slide="3"><a href="#" rel="Connect">Connect</a></li>
      </ul>
    </div>
  </div>
</nav>